In [1]:
import pandas as pd
import seaborn as sns
from statsmodels import api as sm
from matplotlib import pyplot as plt
from pandas.plotting import register_matplotlib_converters
import os
import numpy as np
import datetime

In [11]:
df = pd.read_csv( os.path.join('csv_label', 'learning_data_10.csv') )
df=df[df['day']<=10]
df

         original  label  time  day
0            53.4      0    15    0
1            52.8      0    15    0
2            52.8      0    15    0
3            53.2      0    15    0
4            53.6      0    15    0
...           ...    ...   ...  ...
3995345      45.9      0     5    9
3995346      45.6      0     5    9
3995347      45.8      0     5    9
3995348      45.7      0     5    9
3995349      45.9      0     5    9

[3995350 rows x 4 columns]

In [12]:
df.loc[(df['time']<23)&(df['time']>=6), 't']='day'
df.loc[(df['time']>=23)|(df['time']<6), 't']='night'
df

         original  label  time  day      t
0            53.4      0    15    0    day
1            52.8      0    15    0    day
2            52.8      0    15    0    day
3            53.2      0    15    0    day
4            53.6      0    15    0    day
...           ...    ...   ...  ...    ...
3995345      45.9      0     5    9  night
3995346      45.6      0     5    9  night
3995347      45.8      0     5    9  night
3995348      45.7      0     5    9  night
3995349      45.9      0     5    9  night

[3995350 rows x 5 columns]

In [13]:
def make_data(x, str):
    x=pd.DataFrame(x)
    window=10
    for i in range(1, window):
        column=f'{str}_lag{i}'
        x[column]=x[str].shift(i)
    
#     for i in range(-1, -window, -1):
#         column=f'{str}_lag{i}'
#         x[column]=x[str].shift(i)   
    return x

lag=[] 
for str in ['original']:
    lag.append(make_data(df[str], str))

# lag.append(df['trend'])
# lag.append(df['seasonal'])
# lag.append(df['resid'])
lag.append(df['t'])
lag.append(df['day'])
lag.append(df['label'])
df_add_lag=pd.concat(lag, axis=1)
df=df_add_lag.dropna().reset_index(drop=True)
df

,original,original_lag1,original_lag2,original_lag3,original_lag4,original_lag5,original_lag6,original_lag7,original_lag8,original_lag9,t,day,label
0,55.7,55.5,55.7,54.7,54.0,53.6,53.2,52.8,52.8,53.4,day,0,0
1,55.6,55.7,55.5,55.7,54.7,54.0,53.6,53.2,52.8,52.8,day,0,0
2,55.8,55.6,55.7,55.5,55.7,54.7,54.0,53.6,53.2,52.8,day,0,0
3,55.7,55.8,55.6,55.7,55.5,55.7,54.7,54.0,53.6,53.2,day,0,0
4,55.0,55.7,55.8,55.6,55.7,55.5,55.7,54.7,54.0,53.6,day,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995336,45.9,45.6,45.4,45.9,46.0,45.7,45.4,45.5,45.8,45.9,night,9,0
3995337,45.6,45.9,45.6,45.4,45.9,46.0,45.7,45.4,45.5,45.8,night,9,0
3995338,45.8,45.6,45.9,45.6,45.4,45.9,46.0,45.7,45.4,45.5,night,9,0
3995339,45.7,45.8,45.6,45.9,45.6,45.4,45.9,46.0,45.7,45.4,night,9,0
3995340,45.9,45.7,45.8,45.6,45.9,45.6,45.4,45.9,46.0,45.7,night,9,0

In [14]:
from sklearn.ensemble import RandomForestClassifier
import warnings
from sklearn.metrics import classification_report, f1_score, accuracy_score, precision_score, recall_score
from sklearn.exceptions import UndefinedMetricWarning
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
import pandas as pd
import os
import numpy as np
import support 

def under_sampling(x):
    import warnings
    import pandas as pd
    import os
    warnings.simplefilter('ignore', pd.core.common.SettingWithCopyWarning)
    df = x
    x_majority=df.loc[df.iloc[:,-1]==0]
    x_minority=df.loc[df.iloc[:,-1]==1]
    from sklearn.cluster import KMeans
    km = KMeans(random_state=1, n_clusters=10)
    km.fit(x_majority.iloc[:, :-1])
    x_majority['Cluster'] = km.predict(x_majority.iloc[:, :-1])
    ratio = x_majority['Cluster'].value_counts() / x_majority.shape[0]
    n_sample_ary = (ratio * x_minority.shape[0]).sort_index().astype('int64')
    df_Xs=[]
    for i, n_sample in enumerate(n_sample_ary):
        #重複を許すか許さないかで変わるのか？
        df_Xs.append(x_majority[x_majority['Cluster']==i].sample(n=n_sample, replace=True))

    df_Xs.append(x_minority)
    x=pd.concat(df_Xs, sort=True)
    x=x.drop('Cluster', axis=1)
    
    return x

def calc_avg(x, y):
    import pandas as pd
    import os
    df_x=pd.DataFrame(x)
    df_y=pd.DataFrame(y)
    df_x_raw=df_x['original']
    raw_df=pd.concat([df_x_raw, df_y], axis=1)
    raw_df.columns=range(raw_df.shape[1])
    df_ex=raw_df.loc[raw_df[1]==0]
    N=len(df_ex)
    Leq=10*np.log10(np.sum(np.power(10, df_ex[0]/10)))-10*np.log10(N)
    return Leq

def calc_avg2(x, y):
    import pandas as pd
    import os
    df_x=pd.DataFrame(x)
    df_y=pd.DataFrame(y)
    df_x_raw=df_x['original']
    raw_df=pd.concat([df_x_raw, df_y], axis=1)
    raw_df.columns=range(raw_df.shape[1])
    df_ex=raw_df
    N=len(df_ex)
    Leq=10*np.log10(np.sum(np.power(10, df_ex[0]/10)))-10*np.log10(N)
    return Leq

In [6]:
x = df[ df.columns[ :-1 ] ]
y=  df[ df.columns[ -1 ] ]
va_period_list=list(set(df['day']))

pr=[]
re=[]
f1 = []
ac = []
y_Leq=[]
pred_Leq=[]
no_Leq=[]
n = []

for va_period in va_period_list:
    is_tr=x['day']!=va_period
    is_va=x['day']==va_period
    df_x=x[x.columns[:-1]]
    x_train, x_test = df_x[is_tr], df_x[is_va]
    y_train, y_test = y[is_tr], y[is_va]

    # 学習データだけダウンサンプリング
    x_train_array=x_train[x_train.columns[:-1]]
    train_df=pd.concat([x_train_array, y_train], axis=1)
    train_us=under_sampling(train_df)
    index = train_us.index.tolist()
    x_train=x_train.loc[index, :]
    y_train=y_train.loc[index]
    
    x_train_day=x_train[x_train['t']=='day'][x_train.columns[:-1]]
    y_train_day=y_train[x_train['t']=='day']
    x_train_night=x_train[x_train['t']=='night'][x_train.columns[:-1]]
    y_train_night=y_train[x_train['t']=='night']
    
    
    rcf_day = RandomForestClassifier(n_estimators=10, max_depth=5, max_features='sqrt', random_state=1234)
    rcf_day.fit(x_train_day, y_train_day)
    rcf_night = RandomForestClassifier(n_estimators=10, max_depth=5, max_features='sqrt', random_state=1234)
    rcf_night.fit(x_train_night, y_train_night)
    
    display(x_test)
    z_list=[]
    for i in range(len(x_test)):
        if x_test.iloc[i, -1]=='day':
            z=rcf_day.predict(pd.DataFrame(x_test.iloc[[i],:-1]))
        else:
            z=rcf_night.predict(pd.DataFrame(x_test.iloc[[i],:-1]))
        z_list.append(z)
    z=np.concatenate(z_list)
        
    pr.append( precision_score( y_test, z ) )
    re.append( recall_score( y_test, z) )
    f1.append( f1_score( y_test, z ) )
    ac.append( accuracy_score( y_test, z ) )
    n.append( len( x_test ) / len( x ) )

    #等価騒音レベル計算
    no_Leq.append(calc_avg2(x_test, y_test))
    y_Leq.append(calc_avg(x_test, y_test))
    pred_Leq.append(calc_avg(x_test, z))
    
print( 'CV Score:' )
print( '  Precision Score = %f'%( np.average( pr, weights=n ) ) )
print( '  Recall Score = %f'%( np.average( re, weights=n ) ) )
print( '  F1 Score = %f'%( np.average( f1, weights=n ) ) )
print( '  Accuracy Score = %f'%( np.average( ac, weights=n ) ) )
print( '  no_Leq = %f'%( np.average( no_Leq, weights=n ) ) )
print( '  y_Leq = %f'%( np.average( y_Leq, weights=n ) ) )
print( '  pred_Leq = %f'%( np.average( pred_Leq, weights=n ) ) )

In [15]:
x = df[ df.columns[ :-3 ] ].values
y=  df[ df.columns[ -1 ] ].values
print('train:', len(x))
print('test:', len(x))

# 学習データだけダウンサンプリング
y_data=y[:, np.newaxis]
data=np.concatenate([x, y_data], 1)
train_df=pd.DataFrame(data)
train_us=under_sampling(train_df)
index = train_us.index.tolist()
x_train=x[index]
y_train=y[index]

rcf = RandomForestClassifier(n_estimators=10, max_depth=5, max_features='sqrt', random_state=1234)
rcf.fit(x_train, y_train)
z= rcf.predict(x)

    
print( 'Score:' )
print( '  Precision Score = %f'%( precision_score( y, z )) )
print( '  Recall Score = %f'%(  recall_score( y, z) ))
print( '  F1 Score = %f'%( f1_score( y, z )  ) )
print( '  Accuracy Score = %f'%( accuracy_score( y, z ) ) )
print( '  no_Leq = %f'%( calc_avg2(x, y) ) )
print( '  y_Leq = %f'%( calc_avg(x, y) ) )
print( '  pred_Leq = %f'%( calc_avg(x, z) ) )

train: 3995341
test: 3995341
Score:
  Precision Score = 0.244592
  Recall Score = 0.926199
  F1 Score = 0.386987
  Accuracy Score = 0.630521

KeyError: 'original'